[package]
name = 'ubus-serde'
version = '0.1.0'
authors = ['Bruno Tavares <connect+github@bltavares.com>']
edition = '2018'

[dependencies]
serde = '1.0.118'
serde_json = '1.0.60'

[dependencies.ubus]
path = '../ubus'
