[package]
name = 'ubus-sys'
version = '0.1.0'
authors = ['Bruno Tavares <connect+github@bltavares.com>']
edition = '2018'
links = 'ubus'

[build-dependencies]
pkg-config = '0.3.17'
bindgen = '0.53.2'
cc = '1.0.52'

[dependencies]
